version: "3"

networks:
  sparql:
    driver: bridge
services:
  blazegraph:
    image: blazegraph:2.1.5
    ports:
      - "8090:8080"
    volumes:
      - "$PWD/blazegraph/RWStore.properties:/RWStore.properties"
      - "$PWD/data/:/data"
    networks:
      - sparql
  rdf4j:
    image: eclipse/rdf4j-workbench:amd64-latest
    ports:
      - "8091:8080"
    environment: 
      - JAVA_OPTS="-Xms1g -Xmx4g"
    volumes:
      - "$PWD/data/rdf4j:/var/rdf4j"
      - "$PWD/data/rdf4j/logs:/usr/local/tomcat/logs"
    networks:
      - sparql
  vocbench3:
    build: ./vocbench3
    image: vocbench
    ports:
    - "8092:1979"
    volumes:
    - "$PWD/data/stdata:/opt/vocbench3/data"
    networks:
      - sparql
  trifid:
    image: zazuko/trifid
    ports:
      - "8093:8080"
    depends_on:
      - blazegraph
    volumes:
      - "$PWD/trifid/config-trifid.json:/app/config-trifid.json"
    environment:
  #    - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DEBUG=trifid:*
      - TRIFID_CONFIG=/config-trifid.json
      - SPARQL_ENDPOINT_URL=http://blazegraph:8080/bigdata/namespace/organizations/sparql
      - DATASET_BASE_URL=https://data.meemoo.be/
    networks:
      - sparql
  hypergraphql:
    build: ./hypergraphql
    image: hypergraphql
    ports:
      - "8094:8081"
    networks:
      - sparql

      